# Generated by Django 5.2.3 on 2025-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcarepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogcare_images/'),
        ),
    ]
