# Generated by Django 5.2.3 on 2025-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0002_dogcarepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcarepost',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogcarepost',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
