# Generated by Django 5.2.3 on 2025-06-25 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0003_dogcarepost_date_from_dogcarepost_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcarepost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
