# Generated by Django 5.2.3 on 2025-06-26 18:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0004_alter_dogcarepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dogcarepost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='care4dogs/default', max_length=255, null=True, verbose_name='image'),
        ),
    ]
