# Generated by Django 5.2.3 on 2025-06-26 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0005_alter_dogcarepost_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
