# Generated by Django 5.2.3 on 2025-06-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0006_alter_dogcarepost_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcarepost',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
