# Generated by Django 5.2.3 on 2025-06-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcare', '0008_dogcarepost_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dogcarepost',
            name='date_to',
            field=models.DateField(),
        ),
    ]
